# Generated by Django 2.1.4 on 2018-12-31 11:09

from django.db import migrations, models
import pollexe.utils


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181230_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=pollexe.utils.get_user_image_name),
        ),
    ]
