# Generated by Django 2.1.4 on 2018-12-31 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, max_length=250)),
                ('images', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('demo_link', models.URLField(blank=True)),
                ('affiliate_link', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_feature', models.BooleanField(default=False)),
                ('timestimp', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatestimp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='product.ProductCategory'),
        ),
    ]
