# Generated by Django 2.1.4 on 2018-12-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20181231_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='host_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='affiliate_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
