# Generated by Django 2.1.4 on 2019-01-04 10:30

from django.conf import settings
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190104_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(product.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
