# Generated by Django 2.1.4 on 2018-12-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
