# Generated by Django 2.1.4 on 2018-12-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('collection', 'Collection'), ('review', 'Review')], default='collection', max_length=20),
        ),
    ]
