# Generated by Django 2.1.4 on 2019-01-09 13:27

from django.db import migrations, models
import django.utils.timezone
import pollexe.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181231_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pollexe.utils.get_image_dir_and_name),
        ),
        migrations.AlterField(
            model_name='blog',
            name='timestimp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updatestimp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
