# Generated by Django 2.1.4 on 2019-01-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag_list',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
