# Generated by Django 2.1.4 on 2019-01-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190111_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag_list',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
