# Generated by Django 2.1.4 on 2019-01-11 15:52

from django.db import migrations, models
import pollexe.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190111_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pollexe.utils.get_image_dir_and_name),
        ),
    ]
