# Generated by Django 2.1.4 on 2019-01-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190111_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('pending', 'Pending'), ('created', 'Created')], default='created', max_length=25),
        ),
    ]
