# Generated by Django 2.1.4 on 2019-01-17 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestimp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
