# Generated by Django 2.1.4 on 2019-01-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_option', '0003_auto_20190104_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(max_length=100),
        ),
    ]
