# Generated by Django 2.1.4 on 2019-01-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_option', '0004_auto_20190111_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoption',
            name='social',
        ),
        migrations.AddField(
            model_name='appoption',
            name='social',
            field=models.ManyToManyField(blank=True, null=True, to='app_option.SocialLink'),
        ),
    ]
