# Generated by Django 2.1.4 on 2019-01-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_option', '0005_auto_20190111_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoption',
            name='social',
        ),
    ]
